### ISSUE TITLE
Rebase config on top of new config / update deprecated otions

### ISSUE THREAD

**Issue by iokiwi** [nzpug/chat#18]
Going to take a brand new auto generated config and port values across, replacing deprecated options as I go.

For example

Old/Current config:
```yaml
# The trusted servers to download signing keys from.
perspectives:
  servers:
    "matrix.org":
      verify_keys:
        "ed25519:auto":
          key: "Noi6WqcDj0QmPxCNQqgezwTlBKrfqehY1u2FyWP9uYw"
```

New config:
```yaml
# This setting supercedes an older setting named `perspectives`. The old format
# is still supported for backwards-compatibility, but it is deprecated.
#
trusted_key_servers:
  - server_name: "matrix.org"
```
